# Generated by Django 5.1.1 on 2024-09-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_ingrediente_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="burger",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
