# Generated by Django 5.1.1 on 2024-09-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0003_alter_burger_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="burger",
            name="id",
            field=models.CharField(
                editable=False, max_length=10, primary_key=True, serialize=False
            ),
        ),
    ]
